name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check for index.html
      id: index-html
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: "index-html"
        command: "find . -name index.html"
        expected-output: ./index.html
        comparison-method: exact
        max-score: 1
    - name: Validate HTML
      id: validate-html
      uses: Cyb3r-Jak3/html5validator-action
      with:
        root: .
        
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INDEX-HTML_RESULTS: "${ steps.index-html.outputs.result }}"
        VALIDATE-HTML_RESULTS: "${ steps.validate-html.outputs.result }}"
      with:
        runners: index-html, validate-html